### ISSUE TITLE
Deleted tabs don't delete!

### ISSUE THREAD

**Issue by cynkron** [RJHsiao/ListOpenedTabs#4]
I work with LOTS of tabs, and I so appreciate this app as Chrome doesn't have a tab list like Firefox does, but when I try to use this extension to close no-longer-needed tabs, they disappear from the drop down, but then when leave the drop down and go back, they are often mostly back on the list (and not actually closed).

**Comment by RJHsiao** [comment]
@cynkron 
I can't reproduce this issue, can you give more information like Google Chrome version, OS version, how many tabs you were opening, console logs from development tools, etc.?

**Comment by cynkron** [comment]
I have had your extension on two machines for some time, one Win 7 and one
Win 10 and this is an issue on both.  I often have 20-40 tabs open in
Chrome and would like to reliably use your extension to close unneeded tabs
since after a certain number I can't even see tabs to close them anymore,
but as described, sometimes closing from the drop down works and often it
does not.  My current Chrome version is Version 55.0.2883.87 m but this has
been happening since installation, so I imagine I've been through several
Chrome versions.  Let me know if you need anything else.
ᐧ

_____

Cynthia Koan
Computer Coach and Technician
Voice:  360-385-4234
Scheduling:  www.schedulecynthia.com

**Comment by RJHsiao** [comment]
@cynkron 
I still can't reproduce this issue by following your description.

Have you ever try to re-install my extension, disable other extensions, or install my extension only on a all-new Google Chrome?

It will be helpful if you can provide some console logs from development tools panel when the issue was happening.
