### ISSUE TITLE
Usability problem

### ISSUE THREAD

**Issue by sloanlance** [RJHsiao/ListOpenedTabs#6]
The currently active tab and the selected tab are both colored with similar shades of blue.  Please change the color of the current active tab to green.  Also, give the user an options interface to pick the colors they prefer.

**Comment by RJHsiao** [comment]
Why green?
I'm not good at UI/UX design, but I never see that using green on menu UI design without really special reason.

**Comment by sloanlance** [comment]
Which color would you prefer?

I chose green because of its positive connotation.  Like green on a traffic light or status indicator.  For example, see all the green elements here on **_this_** issue page, like the "Open" indicators, "Comment" button, and "New Issue" button.  Red was another important color option, but it's too negative.

The important thing is that it's much different from the blue color used for the list items with hover or active status.  If you want to choose some other color, I don't mind.  It just needs to be different than the color of the other elements of your extension.

A better solution would be to provide an options interface that lets the user pick better colors than your defaults.

**Comment by RJHsiao** [comment]
1. Blue. It's usually used in UI/UX design to show about "primary", and it looks more comfortable.
The actual name I used is azure blue. 

2. Green is still not a good choice. It's usually used in UI/UX design to show "successful status" and "safe action" only, but not "primary".
And the green you chose (`rgb(0, 255, 127)`) is too bright to use. It looks like you haven't checked the looks before you create #7, right?

3. Actually the color of active-state item and hover-state item are different... not only about the code, but also the looks.

4. I'll think about it if there are more than 3 people require this feature.

Anyway, thanks for your suggestion.
