### ISSUE TITLE
add badge to show tab count

### ISSUE THREAD

**Issue by insaner** [RJHsiao/ListOpenedTabs#9]
Hi, it would be great to add a badge to the button in order to show the tab count for the current window. Fortunately, I already wrote the code for this, and have added it to my fork. Let me know how you would like me to proceed.

**Comment by RJHsiao** [comment]
Hi @insaner 
Thanks for your suggestion!
I think create a pull request will very helpful for me if you already coding for that. 👍

**Comment by insaner** [comment]
Great! I'm not very familiar with how to do things in github as I rarely use it, but I will try to do that. Let me know if I did it right.

**Comment by insaner** [comment]
I'm so sorry if I flooded your inbox/notifications (does github send notifications about forks?) while I was figuring out how to put the code up, remove any unnecessary code, etc, before the pull request. Please do let me know if I did it right, and everything is ok.

**Comment by RJHsiao** [comment]
Sorry to reply too late, and never mind about my inbox.
I'll review your PR ASAP.
Thanks for your contribution. 👍

**Comment by insaner** [comment]
My pleasure! Sorry again if you did get a bunch of notifications, (did you?) I'm still figuring this whole github thing out. Let me know what you think of the changes, and thanks again for the great work!

**Comment by insaner** [comment]
Hi, any updates? Does the commit look ok?

**Comment by RJHsiao** [comment]
Hi @insaner 
Thanks for your PR.
I already reviewed the code and left some comments.
Please try to resolve them, thank you :)

**Comment by insaner** [comment]
Will do, thanks!

**Comment by RJHsiao** [comment]
Well done!
I'll release new version ASAP.

**Comment by RJHsiao** [comment]
@insaner 
New version released, thanks for your contribution.
